# Generated by Django 3.1.7 on 2021-06-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='name',
            new_name='first_name',
        ),
    ]
